[package]
name = "palm-launcher"
version = "0.53.0-rc.1"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["rt-multi-thread", "rt", "macros"] }
serde = { version = "1.0.228", features = ["derive"] }
# stardust-xr-asteroids = { git = "https://github.com/StardustXR/asteroids", version="0.52" }
# stardust-xr-fusion = { git = "https://github.com/StardustXR/core", version="0.52" }
# gluon-ipc = { git = "https://github.com/stardustxr/gluon-ipc" }
# stardust-xr-molecules = { git = "https://github.com/StardustXR/molecules", version="0.52" }
# protostar-launcher = { git = "https://github.com/StardustXR/protostar", version="0.1" }
stardust-xr-asteroids = "0.53.0-rc.1"
stardust-xr-fusion = "0.53.0-rc.1"
gluon-ipc = "0.1.1"
stardust-xr-molecules = "0.53.0-rc.1"
protostar-launcher = { git = "https://github.com/StardustXR/protostar", version="0.1" }

glam = { version = "0.33.0", features = ["mint", "serde"] }
tokio-stream = "0.1.18"
tracing = "0.1.44"
